/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

/**
 *
 * @author Pc
 */
public class menuDoctor extends javax.swing.JFrame {

    /**
     * Creates new form Doctor
     */
    public menuDoctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbutonPacientes = new javax.swing.JButton();
        jButtonCitas = new javax.swing.JButton();
        jButtonServicios = new javax.swing.JButton();
        jButtonHospitales = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbutonPacientes.setText("Pacientes");
        jbutonPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutonPacientesActionPerformed(evt);
            }
        });
        jPanel1.add(jbutonPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jButtonCitas.setText("Citas");
        jButtonCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCitasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 90, -1));

        jButtonServicios.setText("Servicios");
        jButtonServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonServiciosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jButtonHospitales.setText("Hospitales");
        jButtonHospitales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHospitalesActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHospitales, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutonPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutonPacientesActionPerformed
       
        pacientes VentanaPacientes = new pacientes();
        VentanaPacientes.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jbutonPacientesActionPerformed

    private void jButtonCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCitasActionPerformed
        
        Citas AbrirVentanaCitas = new Citas();
        AbrirVentanaCitas.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButtonCitasActionPerformed

    private void jButtonServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonServiciosActionPerformed
        
        Servicios AbrirVentanaServicios = new Servicios();
        AbrirVentanaServicios.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButtonServiciosActionPerformed

    private void jButtonHospitalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHospitalesActionPerformed
        
        Hospitales AbrirVentanaHospitales = new Hospitales();
        AbrirVentanaHospitales.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButtonHospitalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCitas;
    private javax.swing.JButton jButtonHospitales;
    private javax.swing.JButton jButtonServicios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbutonPacientes;
    // End of variables declaration//GEN-END:variables
}
