/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RolDoctor;

import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import login.Conexion;


public class DoctorOperaciones extends javax.swing.JFrame {

    /**
     * Creates new form Servicios
     */
    
    Conexion BaseDatos = new Conexion();
    Connection ingresa = Conexion.getConnection();
        ResultSet resultado;

    public DoctorOperaciones() {
        initComponents();
    }

    void AgregaOperacion(){
        String TipoOperacion = (String) cboTipoOperacion.getSelectedItem();
        String insertar = "INSERT INTO operaciones (idHospital, idDoctor, idPaciente, tipoOperacion) values (?,?,?,?)";
        try{
            java.sql.PreparedStatement registra = ingresa.prepareCall(insertar);
            registra.setString(1, txtIdHospital.getText());
            registra.setString(2, txtIdDoctor.getText());
            registra.setString(3, txtIdPaciente.getText());
            registra.setString(4, TipoOperacion);
            int agregar = registra.executeUpdate();
            if (agregar > 0){
                JOptionPane.showMessageDialog(this, "Operación agregada exitosamente","Bien", JOptionPane.QUESTION_MESSAGE);
            }else{
                 JOptionPane.showMessageDialog(this, "Operación NO agregada","Atención", JOptionPane.ERROR_MESSAGE);
            }
        } catch(Exception e){
        } finally {
            txtidoperacion.setText("");
                txtIdHospital.setText("");
                txtIdDoctor.setText("");
                txtIdPaciente.setText("");
                cboTipoOperacion.setSelectedItem("");
        }
   }
    
 void consultarDatosOperacion(){
            String query = "SELECT * FROM operaciones WHERE idOperacion = '"+txtidoperacion.getText().trim()+"'";
            try {
                java.sql.Statement st = ingresa.createStatement();
                java.sql.ResultSet rs = st.executeQuery(query);
                while (rs.next()) {
                    txtIdHospital.setText(rs.getString("idHospital"));
                    txtIdDoctor.setText(rs.getString("idDoctor"));
                    txtIdPaciente.setText(rs.getString("idPaciente"));
                    cboTipoOperacion.setSelectedItem(rs.getString("tipoOperacion"));
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboTipoOperacion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtidoperacion = new javax.swing.JTextField();
        txtIdHospital = new javax.swing.JTextField();
        txtIdDoctor = new javax.swing.JTextField();
        txtIdPaciente = new javax.swing.JTextField();
        btnIngresarOperaciones = new javax.swing.JButton();
        btnConsultarOperaciones = new javax.swing.JButton();
        btnlistaOperaciones = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ID Operacion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ID Hospital");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("ID Doctor");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("ID Paciente");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        cboTipoOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ambulatoria", "Maxilofacial", "Vesicula" }));
        jPanel1.add(cboTipoOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 110, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Tipo de Operación");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
        jPanel1.add(txtidoperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 120, 30));
        jPanel1.add(txtIdHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 120, 30));
        jPanel1.add(txtIdDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 120, 30));
        jPanel1.add(txtIdPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 120, 30));

        btnIngresarOperaciones.setText("Ingresar");
        btnIngresarOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarOperacionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresarOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        btnConsultarOperaciones.setText("Consultar");
        btnConsultarOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarOperacionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        btnlistaOperaciones.setText("Consultar Lista");
        btnlistaOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistaOperacionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnlistaOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Cirugía y Operación");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        menuDoctor VentanaMenuDoctor = new menuDoctor();
        VentanaMenuDoctor.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnlistaOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistaOperacionesActionPerformed
        
        ListaOperaciones VentanaListaOperaciones = new ListaOperaciones();
        VentanaListaOperaciones.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnlistaOperacionesActionPerformed

    private void btnIngresarOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarOperacionesActionPerformed
        // TODO add your handling code here:
        AgregaOperacion();
    }//GEN-LAST:event_btnIngresarOperacionesActionPerformed

    private void btnConsultarOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarOperacionesActionPerformed
        // TODO add your handling code here:
        consultarDatosOperacion();
    }//GEN-LAST:event_btnConsultarOperacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorOperaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarOperaciones;
    private javax.swing.JButton btnIngresarOperaciones;
    private javax.swing.JButton btnlistaOperaciones;
    private javax.swing.JComboBox<String> cboTipoOperacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtIdDoctor;
    private javax.swing.JTextField txtIdHospital;
    private javax.swing.JTextField txtIdPaciente;
    private javax.swing.JTextField txtidoperacion;
    // End of variables declaration//GEN-END:variables
}
