/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RolDoctor;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import login.Conexion;


public class ListaInternamiento extends javax.swing.JFrame {
Conexion BaseDatos = new Conexion();
    Connection ingresa = Conexion.getConnection();
    CallableStatement SeleccionaTabla;
    ResultSet resultado;
    /**
     * Creates new form ListaInternamiento
     */
    public ListaInternamiento() {
        initComponents();
    }
public void CargarListaInternamientos(){
            DefaultTableModel tablaOperaciones= new DefaultTableModel();
       try{
       tablaOperaciones.addColumn("ID Internamiento");
       tablaOperaciones.addColumn("ID Hospital");
       tablaOperaciones.addColumn("ID Paciente");
       tablaOperaciones.addColumn("Motivo del Internamiento");
       SeleccionaTabla=ingresa.prepareCall("Select * from internamientos");
       resultado=SeleccionaTabla.executeQuery();
       while (resultado.next()){
       Object datos[]=new  Object[4];
       for (int filas=0; filas<4; filas++){
           datos[filas]=resultado.getString(filas+1);
       }
       tablaOperaciones.addRow(datos);
       }
       this.jtInternamientos.setModel(tablaOperaciones);//jTable---jdatos
       }catch (Exception e){}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtInternamientos = new javax.swing.JTable();
        btnInternamientoRegresar = new javax.swing.JButton();
        btnConsultarListaInternamiento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Lista de internamientos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jtInternamientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtInternamientos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 520, 340));

        btnInternamientoRegresar.setText("Regresar");
        btnInternamientoRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInternamientoRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnInternamientoRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, -1, -1));

        btnConsultarListaInternamiento.setText("Ver Internamientos");
        btnConsultarListaInternamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarListaInternamientoActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarListaInternamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 4, 540, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInternamientoRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInternamientoRegresarActionPerformed
       
        DoctorInternamientos VentanaInternamientos = new DoctorInternamientos();
        VentanaInternamientos.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnInternamientoRegresarActionPerformed

    private void btnConsultarListaInternamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarListaInternamientoActionPerformed
        // TODO add your handling code here:
        CargarListaInternamientos();
    }//GEN-LAST:event_btnConsultarListaInternamientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaInternamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaInternamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaInternamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaInternamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaInternamiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarListaInternamiento;
    private javax.swing.JButton btnInternamientoRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtInternamientos;
    // End of variables declaration//GEN-END:variables
}
