/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RolSecretario;

import java.sql.Connection;
import login.Conexion;

/**
 *
 * @author Pc
 */
public class Hospitales extends javax.swing.JFrame {
Conexion BaseDatos = new Conexion();
    Connection ingresa = Conexion.getConnection();

    /**
     * Creates new form Hospitales
     */
    public Hospitales() {
        initComponents();
    }
public void consultarDatosHospital() {
        
String idHospital =  (String) cboIdHospita.getSelectedItem();

        String query = "SELECT * FROM hospitales where idHospital = '" + idHospital + "'";
        try {
            java.sql.Statement st = ingresa.createStatement();
            java.sql.ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
               lblPropiedad1.setText(rs.getString("tipoPropiedad"));
                lblConsultorios1.setText(rs.getString("consultorios"));
               lblniveles.setText(rs.getString("niveles"));
               lblColor1.setText(rs.getString("color"));
                lblCirugias.setText(rs.getString("tipoCirugias"));
                lbldescripcion.setText(rs.getString("descripcion"));
            }
        } catch (Exception e) {
            System.out.println(e);
        } 
    }

private void cargarIdHospital() {
        // TODO Auto-generated method stub

        String query = "SELECT idHospital FROM hospitales";

        try {
            java.sql.Statement st = ingresa.createStatement();
            java.sql.ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                String tmpStrObtenido = rs.getString("idHospital");

                cboIdHospita.addItem(tmpStrObtenido);
            }
// ingresa.close();

        } catch (Exception e) {
            System.out.println("ERROR: Al cargar de la base de datos.");
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnConsultarHospital = new javax.swing.JButton();
        BtnListaHospital = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lbldescripcion = new javax.swing.JLabel();
        lblPropiedad1 = new javax.swing.JLabel();
        lblConsultorios1 = new javax.swing.JLabel();
        lblniveles = new javax.swing.JLabel();
        lblCirugias = new javax.swing.JLabel();
        lblColor1 = new javax.swing.JLabel();
        cboIdHospita = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonMenu.setText("Menú");
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Id Hospital");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tipo de propiedad");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("consultorios");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Niveles");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Color");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tipo de cirugias");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Decsripción");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        btnConsultarHospital.setText("Consultar");
        btnConsultarHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarHospitalActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        BtnListaHospital.setText("Consultar Lista");
        BtnListaHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListaHospitalActionPerformed(evt);
            }
        });
        jPanel1.add(BtnListaHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Hospitales");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        lbldescripcion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbldescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 250, 30));

        lblPropiedad1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lblPropiedad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 200, 30));

        lblConsultorios1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lblConsultorios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 200, 30));

        lblniveles.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lblniveles, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 200, 30));

        lblCirugias.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lblCirugias, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 140, 30));

        lblColor1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lblColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 140, 30));

        cboIdHospita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona" }));
        cboIdHospita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboIdHospitaActionPerformed(evt);
            }
        });
        jPanel1.add(cboIdHospita, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 150, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 450, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        
         menuSecretario VentanaMenuSecretario = new menuSecretario();
        VentanaMenuSecretario.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void BtnListaHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListaHospitalActionPerformed
        
        HospitalesSecretarioLista VentanaHospitalesSecretarioLista = new HospitalesSecretarioLista();
        VentanaHospitalesSecretarioLista.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_BtnListaHospitalActionPerformed

    private void btnConsultarHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarHospitalActionPerformed
        // TODO add your handling code here:
        consultarDatosHospital();
    }//GEN-LAST:event_btnConsultarHospitalActionPerformed

    private void cboIdHospitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboIdHospitaActionPerformed
        // TODO add your handling code here:
        cargarIdHospital();
    }//GEN-LAST:event_cboIdHospitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospitales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospitales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospitales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospitales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hospitales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnListaHospital;
    private javax.swing.JButton btnConsultarHospital;
    private javax.swing.JComboBox<String> cboIdHospita;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCirugias;
    private javax.swing.JLabel lblColor1;
    private javax.swing.JLabel lblConsultorios1;
    private javax.swing.JLabel lblPropiedad1;
    private javax.swing.JLabel lbldescripcion;
    private javax.swing.JLabel lblniveles;
    // End of variables declaration//GEN-END:variables
}
