/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RolSecretario;

import login.Conexion;
import login.Inicio;
public class menuSecretario extends javax.swing.JFrame {

    /**
     * Creates new form Doctor
     */
    public menuSecretario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbutonPacientes = new javax.swing.JButton();
        jButtonCitas = new javax.swing.JButton();
        btnOperaciones = new javax.swing.JButton();
        jButtonHospitales = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        btnInternamientos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbutonPacientes.setText("Pacientes");
        jbutonPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutonPacientesActionPerformed(evt);
            }
        });
        jPanel1.add(jbutonPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jButtonCitas.setText("Citas");
        jButtonCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCitasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 90, -1));

        btnOperaciones.setText("Operaciones y Cirugías");
        btnOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperacionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jButtonHospitales.setText("Hospitales");
        jButtonHospitales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHospitalesActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHospitales, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        btnUsuario.setText("Cambiar de usuario");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        btnInternamientos.setText("Internamientos");
        btnInternamientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInternamientosActionPerformed(evt);
            }
        });
        jPanel1.add(btnInternamientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutonPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutonPacientesActionPerformed
       
        pacientes VentanaPacientes = new pacientes();
        VentanaPacientes.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jbutonPacientesActionPerformed

    private void jButtonCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCitasActionPerformed
        
        Citas AbrirVentanaCitas = new Citas();
        AbrirVentanaCitas.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButtonCitasActionPerformed

    private void btnOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperacionesActionPerformed
        
        Operaciones AbrirVentanaServicios = new Operaciones();
        AbrirVentanaServicios.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnOperacionesActionPerformed

    private void jButtonHospitalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHospitalesActionPerformed
        
        Hospitales AbrirVentanaHospitales = new Hospitales();
        AbrirVentanaHospitales.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButtonHospitalesActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        
        Inicio AbrirVentanaLogin = new Inicio();
        AbrirVentanaLogin.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnInternamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInternamientosActionPerformed
        
        Internamientos VentanaInternamientos = new Internamientos();
        VentanaInternamientos.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnInternamientosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuSecretario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInternamientos;
    private javax.swing.JButton btnOperaciones;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JButton jButtonCitas;
    private javax.swing.JButton jButtonHospitales;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbutonPacientes;
    // End of variables declaration//GEN-END:variables
}
