/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RolSecretario;

import java.sql.Connection;
import java.sql.ResultSet;
import login.Conexion;

/**
 *
 * @author Pc
 */
public class Operaciones extends javax.swing.JFrame {
Conexion BaseDatos = new Conexion();
    Connection ingresa = Conexion.getConnection();
        ResultSet resultado;

    /**
     * Creates new form Servicios
     */
    public Operaciones() {
        initComponents();
    }

     void consultarDatosOperacion(){
            String query = "SELECT * FROM operaciones WHERE idOperacion = '"+txtidoperacion.getText().trim()+"'";
            try {
                java.sql.Statement st = ingresa.createStatement();
                java.sql.ResultSet rs = st.executeQuery(query);
                while (rs.next()) {
                    lblOperacionHospital.setText(rs.getString("idHospital"));
                    lblOperacionDoctor.setText(rs.getString("idDoctor"));
                    lblOperacionPaciente.setText(rs.getString("idPaciente"));
                    lblTipoOperacion.setText(rs.getString("tipoOperacion"));
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtidoperacion = new javax.swing.JTextField();
        btnConsultarOperaciones = new javax.swing.JButton();
        btnlistaOperaciones = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblTipoOperacion = new javax.swing.JLabel();
        lblOperacionHospital = new javax.swing.JLabel();
        lblOperacionDoctor = new javax.swing.JLabel();
        lblOperacionPaciente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ID Operacion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ID Hospital");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("ID Doctor");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("ID Paciente");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Tipo de Operación");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
        jPanel1.add(txtidoperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 130, 30));

        btnConsultarOperaciones.setText("Consultar");
        btnConsultarOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarOperacionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        btnlistaOperaciones.setText("Consultar Lista");
        btnlistaOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistaOperacionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnlistaOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Operación o Cirugía");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        lblTipoOperacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lblTipoOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 130, 30));

        lblOperacionHospital.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lblOperacionHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 130, 30));

        lblOperacionDoctor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lblOperacionDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 130, 30));

        lblOperacionPaciente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lblOperacionPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        menuSecretario VentanaMenuSecretario = new menuSecretario();
        VentanaMenuSecretario.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnlistaOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistaOperacionesActionPerformed
        
        OperacionesSecretarioLista VentanaOperacionesSecretarioLista = new OperacionesSecretarioLista();
        VentanaOperacionesSecretarioLista.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnlistaOperacionesActionPerformed

    private void btnConsultarOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarOperacionesActionPerformed
        // TODO add your handling code here:
        consultarDatosOperacion();
    }//GEN-LAST:event_btnConsultarOperacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarOperaciones;
    private javax.swing.JButton btnlistaOperaciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblOperacionDoctor;
    private javax.swing.JLabel lblOperacionHospital;
    private javax.swing.JLabel lblOperacionPaciente;
    private javax.swing.JLabel lblTipoOperacion;
    private javax.swing.JTextField txtidoperacion;
    // End of variables declaration//GEN-END:variables
}
